### ISSUE TITLE
Please mark as unofficial

### ISSUE THREAD

**Issue by ajbt200128** [jtmelton/semgrep-idea-plugin#5]
Hello! Great work on this plugin, over at Semgrep we're planning to release an officially supported version of an IntelliJ plugin (see [here](https://github.com/returntocorp/semgrep-intellij)). Feel free to keep this one up, but it'd be very much appreciated if you labeled this as unofficial in the plugin title and description.

**Comment by jtmelton** [comment]
Marked description as unofficial and linked to official.

**Comment by ajbt200128** [comment]
Thanks!
